# Generated by Django 5.1.6 on 2025-02-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerup',
            name='image_url',
        ),
        migrations.AddField(
            model_name='powerup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='powerup_images/'),
        ),
    ]
